{
 "title": "Flink monitoring",
 "tags": [ "nextbreakpoint" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "env", "query": "demo" }
  ]
 },
 "panels": [
  { "title": "Flink Task Managers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flink Task Managers Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "groupByNode(nextbreakpoint.*-flink.$env.*.*.taskmanager.*.Status.JVM.Memory.Heap.Used, 3, 'avg')"
    },
    {
     "target": "groupByNode(nextbreakpoint.*-flink.$env.*.*.taskmanager.*.Status.JVM.Memory.Heap.Max, 3, 'avg')"
    },
    {
     "target": "groupByNode(nextbreakpoint.*-flink.$env.*.*.taskmanager.*.Status.JVM.Memory.Direct.MemoryUsed, 3, 'avg')"
    },
    {
     "target": "groupByNode(nextbreakpoint.*-flink.$env.*.*.taskmanager.*.Status.JVM.Memory.Direct.TotalCapacity, 3, 'avg')"
    }
   ]
  },
  {
   "title": "Flink Task Managers Direct Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "groupByNode(nextbreakpoint.*-flink.$env.*.*.taskmanager.*.Status.JVM.Memory.Direct.MemoryUsed, 3, 'avg')"
    },
    {
     "target": "groupByNode(nextbreakpoint.*-flink.$env.*.*.taskmanager.*.Status.JVM.Memory.Direct.TotalCapacity, 3, 'avg')"
    }
   ]
  },
  {
   "title": "Flink Task Managers CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "groupByNode(nextbreakpoint.*-flink.$env.*.*.taskmanager.*.Status.JVM.CPU.Load, 3, 'avg')"
    }
   ]
  },
  {
   "title": "Flink Checkpoints Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nextbreakpoint.*-flink.$env.*.*.jobmanager.Flink-Streaming-Job.numberOfInProgressCheckpoints, 3, 7)"
    },
    {
     "target": "aliasByNode(nextbreakpoint.*-flink.$env.*.*.jobmanager.Flink-Streaming-Job.numberOfFailedCheckpoints, 3, 7)"
    },
    {
     "target": "aliasByNode(nextbreakpoint.*-flink.$env.*.*.jobmanager.Flink-Streaming-Job.numberOfCompletedCheckpoints, 3, 7)"
    },
    {
     "target": "aliasByNode(nextbreakpoint.*-flink.$env.*.*.jobmanager.Flink-Streaming-Job.totalNumberOfCheckpoints, 3, 7)"
    }
   ]
  },
  {
   "title": "Flink Checkpoints Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nextbreakpoint.*-flink.$env.*.*.jobmanager.Flink-Streaming-Job.fullRestarts, 3, 7)"
    }
   ]
  },
  {
   "title": "Flink Checkpoints Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nextbreakpoint.*-flink.$env.*.*.jobmanager.Flink-Streaming-Job.lastCheckpointSize, 3, 7)"
    }
   ]
  },
  {
   "title": "Flink Checkpoints Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nextbreakpoint.*-flink.$env.*.*.jobmanager.Flink-Streaming-Job.lastCheckpointDuration, 3, 7)"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nextbreakpoint.*-flink.$env.*.*.taskmanager.*.Flink-Streaming-Job.window.*.counter-*.count, 10)"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nextbreakpoint.*-flink.$env.*.*.taskmanager.*.Flink-Streaming-Job.window.*.gauge-*, 10)"
    }
   ]
  }
 ]
}