{
 "title": "Kafka Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Kafka counters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount)",
     "legendFormat": "offline partitions count"
    },
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions)",
     "legendFormat": "underreplicated partitions"
    },
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount)",
     "legendFormat": "active controller count"
    }
   ]
  },
  {
   "title": "Zookeeper counters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_sessionexpirelistener_zookeeperdisconnects_total)",
     "legendFormat": "disconnects total"
    },
    {
     "expr": "sum(kafka_server_sessionexpirelistener_zookeeperauthfailures_total)",
     "legendFormat": "auth failures total"
    },
    {
     "expr": "sum(kafka_server_sessionexpirelistener_zookeepersaslauthentications_total)",
     "legendFormat": "sasl authentication total"
    }
   ]
  },
  {
   "title": "Kafka bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesin_total)",
     "legendFormat": "bytes in total"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesout_total)",
     "legendFormat": "bytes out total"
    }
   ]
  },
  {
   "title": "Kafka topics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_size{topic=~\"abstraction-enriched-users-.*\"})",
     "legendFormat": "abstraction-enriched-users"
    },
    {
     "expr": "sum(kafka_log_size{topic=~\"abstraction-user-events-.*\"})",
     "legendFormat": "abstraction-enriched-users"
    },
    {
     "expr": "sum(kafka_log_size{topic=~\"spoor-bridge-.*\"})",
     "legendFormat": "abstraction-enriched-users"
    },
    {
     "expr": "sum(kafka_log_size{topic=~\"spoor-by-impression-.*\"})",
     "legendFormat": "abstraction-enriched-users"
    }
   ]
  }
 ]
}